"""
Buffer Helper (Target Generation Pipeline)
        Ingests the dense game records generated by SelfPlay.
        Calculates the KataGo-style EMA short-term/lookahead targets across future turn boundaries.
        Strips out unnecessary data to create the compact representation, then pushes it to `buffer.py`.
        """